### ISSUE TITLE
using typings 1.0

### ISSUE THREAD

**Issue by mattqs** [pushrocks/gulp-typings#10]
There are changes in typings version 1.0 https://github.com/typings/typings/releases/tag/v1.0.0. 

When will gulp-typings be using version 1.0?

**Comment by philkunz** [comment]
@mattqs
I'll have a look when I find some time.
Meanwhile PRs are welcome.

**Comment by philkunz** [comment]
v2.x.x on npm now relies on v1.x.x of typings-core.
