### ISSUE TITLE
typings dependency needs updating

### ISSUE THREAD

**Issue by patsissons** [pushrocks/gulp-typings#3]
Getting an error when I pipe into `gulp-typings`:

> Error:  something went wrong: Check if path is correct: `...`

I traced into the module and found that it was the local `typings` dependency that was causing the issue:

> "Unknown dependency: registry:dt/..."

Assuming this new format is not supported in `0.6.8`

**Comment by philkunz** [comment]
I'm on it.

**Comment by philkunz** [comment]
version 1.2.0 with latest deps should publish any minute on npm (given tests run through on travis).

**Comment by philkunz** [comment]
v1.2.0 is published.

**Comment by patsissons** [comment]
awesome thanks!
