### ISSUE TITLE
gulp typings typings

### ISSUE THREAD

**Issue by peltco** [pushrocks/gulp-typings#7]
it would be nice if gulp-typings would have it's own typings entry (so i can write a strongly typed gulpfile.ts)

**Comment by philkunz** [comment]
ok, there some irony in gulp-typings not having typings :) I'll see what I can do tomorrow.

**Comment by philkunz** [comment]
See pushrocks/npmts#10 ... typings generation will be automated with npmts.

**Comment by philkunz** [comment]
v1.3.5 and above bundles auto generated typings.
http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html
