### ISSUE TITLE
is gulp-typings asynchronous, and if so how do I accomodate that?

### ISSUE THREAD

**Issue by dicej** [pushrocks/gulp-typings#8]
In my gulpfile, I have:

```
const gulp = require('gulp')
  , typings = require('gulp-typings')
...
gulp.task('typings',function(){
  gulp.src('./typings.json').pipe(typings());
});
...
gulp.task('editor', ['editor-html', 'typings'], function () {
  return browserify()
         .add('./src/editor/index.ts')
         .plugin(tsify, { noImplicitAny: true })
         .bundle()
         .on('error', function (error) { console.error(error.toString())
                                         process.exit(1) })
         .pipe(source('zote-editor.js'))
         .pipe(gulp.dest('build'))
})
...
```

In my typings.json, I have:

```
{
  "ambientDependencies": {
    "chai": "registry:dt/chai#3.4.0+20160317120654",
    "codemirror": "registry:dt/codemirror#0.0.0+20160317120654",
    "mocha": "registry:dt/mocha#2.2.5+20160317120654"
  }
}
```

When I run `gulp typings` on the command line, a typings directory is created and the type definition files are installed.  However, if I delete that directory and try again with `gulp editor`, I get

```
[11:30:37] Using gulpfile ~/p/zotecode/gulpfile.js
[11:30:37] Starting 'editor-html'...
[11:30:37] Starting 'typings'...
[11:30:37] Finished 'typings' after 8 ms
[11:30:37] Finished 'editor-html' after 95 ms
[11:30:37] Starting 'editor'...
TypeScript error: src/editor/index.ts(1,1): Error TS6053: File 'typings/main.d.ts' not found.
```

I suspect this is because gulp-typings isn't waiting for typings to install stuff before returning control to gulp, so when the editor task runs, the definitions aren't there yet and the TypeScript compiler complains.  Is this the case, and if so, how can I structure things to ensure the definitions are fully installed before a task which depends on them is run?

Thanks.

**Comment by philkunz** [comment]
Yes, you are correct, gulp-typings is async.
You need to return the gulp stream, so gulp knows where to listen for the finish event.
This is standard for gulp.

Regards
Phil from Lossless

**Comment by dicej** [comment]
Ah, of course; thanks for explaining it.  I think I'll actually learn how gulp works before filing any more bugs :)

**Comment by philkunz** [comment]
No problem, glad to help ;)
